version: "3.7"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file:
      - mysql.env
volumes:
  mysql: